# Wrangler configuration for Cloudflare Workers
name = "semantic"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]

# Assets from the dist folder
[site]
bucket = "./dist"

# Environment variables for production
# Set via: wrangler secret put <NAME>
# Or add them here (not recommended for sensitive data)
